---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      app: webapp
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: rdocker11/simplehello:latest
          ports:
            - containerPort: 8080
